import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ConvexClientProvider from "@/src/components/ConvexClientProvider";
import { ClerkProvider } from "@clerk/nextjs";
import Footer from "@/src/components/Footer";
import {Toaster} from "react-hot-toast"
import { StreamVideoProvider } from "./(root)/_components/StreamVideoProvider";
// import y from "../code-symbol.svg?url"
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Code Editor",
  description: "Generated by create next app",
  icons: {
    icon: "/convex.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script src="https://checkout.razorpay.com/v1/checkout.js"></script>
         <link rel="icon" href="/code-symbol.svg" type="image/svg+xml" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased
        bg-gradient-to-b from-gray-900 to-gray-950 text-gray-100 flex flex-col   `}
      >
        <ClerkProvider dynamic>
          <ConvexClientProvider>
           <StreamVideoProvider>
              {children}
            </StreamVideoProvider>
            </ConvexClientProvider>
        </ClerkProvider>
        <Footer/>
        <Toaster/>
         </body>
      
    </html>
  );
}
